source 'https://rubygems.org'
ruby '2.1.2'
gem 'rails', '4.1.2'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '>= 3.0.0.0'
gem 'figaro'
#gem 'simple_form'
gem 'simple_form', '~> 3.1.0.rc1', github: 'plataformatec/simple_form'
gem 'thin'
#gem 'listen', '~> 2.0'
gem 'listen', '2.7.6'
gem "twitter", "5.8.0"
gem 'omniauth-twitter'
gem 'omniauth-facebook'
#gem 'omniauth-facebook', '1.4.0'
#gem "omniauth-google-oauth2"
gem "koala", "~> 1.8.0rc1"
gem "mini_magick"
gem "rmagick"
#gem "gifanime", git: "git@github.com:vaughankg/gifanime.git"
#gem 'twilio-ruby', '~> 3.11'
#gem "google-api-client"
#gem "mogreet"
#gem "picasa"
gem "foreman"
gem 'resque'
#gem 'aws-sdk', '~> 1.0'
gem "daemons-rails"
gem "bitly"
gem "omniauth-smugmug"
gem "ruby-smugmug", git: "git@github.com:vaughankg/ruby-smugmug.git"

gem "pg"

gem "timers"

group :production do
end

group :development do
  gem 'better_errors'
  #gem 'binding_of_caller', :platforms=>[:mri_19, :mri_20, :rbx]
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'rails_layout'
end
group :development, :test do
  gem 'sqlite3'
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.0.0'
end
group :test do
  gem 'capybara'
  #gem 'cucumber-rails', :require=>false
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
end
  gem 'launchy'

