PROJECT_ROOT: <%= ENV['HOME'] %>/Desktop
EVENTS_PATH: <%= ENV['HOME'] %>/Desktop/PhotoboothPopUp Sessions
PRINT_PATH: <%= ENV['HOME'] %>/Desktop/PhotoboothPopUp Print

GIF_MODE: "NO"
MAX_PHOTOS_IN_SET: 6
GIF_DELAY: 30

MOVE_FROM_CAPTURE_FOLDER: "NO"

PRINT_TO_FOLDER: "YES"

SHARE_COPY_EMAIL_SUBJECT: ""
SHARE_COPY_EMAIL_BODY: ""
SHARE_COPY_SOCIAL: ""
SHARE_COPY_TWITTER: ""

# Display photos
IMAGE_WIDTH: 242

BRANDED_IMAGE_WIDTH: 1200
BRANDED_IMAGE_HEIGHT: 1800

BRANDED_IMAGE_WIDTH_GIF: 1200
BRANDED_IMAGE_HEIGHT_GIF: 1800

DISPLAY_IMAGE_WIDTH: 350
DISPLAY_IMAGE_HEIGHT: 525

PRINT_IMAGE_WIDTH: 1200
PRINT_IMAGE_HEIGHT: 1800

GIF_PRINT_MARGIN_TOP: 0
GIF_PRINT_MARGIN_RIGHT: 0
GIF_PRINT_MARGIN_BOTTOM: 0
GIF_PRINT_MARGIN_LEFT: 0

TWITTER_KEY: "w0GY9v8iCCB2I27n7Wrhg"
TWITTER_SECRET: "Cv2v7vjWy8pAg7aST8tpsR4WhJUf3BHPL35GR4XtNo"

FACEBOOK_KEY: "613102788765274"
FACEBOOK_SECRET: "f37a71a54e7a1e4f90feac13376505b4"

BITLY_USERNAME: "pboothup"
BITLY_TOKEN: "eb3ccacb67ab983925bbed37530aaf738fd8f4a0"

# hello@photoboothpopup.com
#SMUGMUG_KEY: "4nesI0wtHo17Q9u8bmudJObQc6blEgfn"
#SMUGMUG_SECRET: "7a2cf5c6827f42c796e7f138f7e05e21"
#SMUGMUG_ACCESS_TOKEN: "e84185662febfd2226cf1cd9e6f98571"
#SMUGMUG_ACCESS_SECRET: "e6ec11546ca328a3de3c76fb0b7587b750c4f434bc30de8e222f6e754c13d48f"
#SMUGMUG_ALBUM_TITLE: "None"

# Test account
#SMUGMUG_KEY: "atHIe9KA1pJMc3pE32Lkse5VYkCKqHZo"
#SMUGMUG_SECRET: "886144bd58dfb7f90fc5668a56d3fb7e"
#SMUGMUG_ACCESS_TOKEN: "9c72d3b807b63ffb9c341613542f217a"
#SMUGMUG_ACCESS_SECRET: "6c49eb2456d682b5c7392e6e14eb95e5aafeb57769bdf878e821159a285b807c"
#SMUGMUG_ALBUM_TITLE: "Test"

# NBC Universal
#SMUGMUG_KEY: "JDlsnqeuFbS6wPLz0DlzWbJYqMqdhQZB"
#SMUGMUG_SECRET: "6adf415dff11fcb8cfbfbdecf7eba3a1"
#SMUGMUG_ACCESS_TOKEN: "4d771e270ec34e0438b2de02f6e8238e"
#SMUGMUG_ACCESS_SECRET: "e78f618b08822aad684c0b3714cbe37be2733ad5979aa6a739d857c44a5cff72"
#SMUGMUG_ALBUM_TITLE: "YOUR ANIMATED GIFS"

# SATISFACTION USA
#SMUGMUG_KEY: "EcmzaOSwcY8jlBYErAdUOdijV62mpa0k"
#SMUGMUG_SECRET: "15db35cb5deeace0635a8ca6db7c6f29"
#SMUGMUG_ACCESS_TOKEN: "3b8d3e7eee87a23bb39a842ff71faf33"
#SMUGMUG_ACCESS_SECRET: "df65de67e77e912ee5e4df9cb46fa6a39698b0ba5d55819722da4040ce5b7d31"
#SMUGMUG_ALBUM_TITLE: "Test1"
